services:
  db:
    image: postgres:14
    container_name: music_db
    env_file:
      - ../backend/infrastructure/env_files/.env.dev
    ports:
      - "5437:5432"
    volumes:
      - music_data:/var/lib/postgresql/data
    networks:
      - music_network
    

  keycloak:
    container_name: keycloak-ms
    image: quay.io/keycloak/keycloak:24.0.2
    ports:
      - "9097:8080"
    env_file:
      - ../backend/infrastructure/env_files/.env.dev
    networks:  
      - music_network
    command: 
      - "start-dev"

networks:
  music_network:
    driver: bridge

volumes:
  music_data:
