services:
  db:
    image: postgres:14
    container_name: music_db
    env_file:
      - ../infrastructure/env_files/.env.dev
    ports:
      - "5437:5432"
    volumes:
      - music_data:/var/lib/postgresql/data
    networks:
      - music_network
    

  keycloak:
    container_name: keycloak-ms
    image: quay.io/keycloak/keycloak:24.0.2
    ports:
      - "9097:8080"
    env_file:
      - ../infrastructure/env_files/.env.dev
    networks:  
      - music_network
    command: 
      - "start-dev"

  audio-streamer:
    container_name: streaming-service
    image: audio-streamer
    build:
      context: ../streamer
    env_file:
     - ../infrastructure/env_files/.env.dev
    ports:
      - "8097:8090"
    volumes:
      - ../streamer/audio-data:/audio-data
    networks:
      - music_network
    

networks:
  music_network:
    driver: bridge

volumes:
  music_data:
