spring:
  application:
    name: mvp
  profiles:
    active: dev



  # DB config
  datasource:
    url: jdbc:postgresql://localhost:5437/music-db
    username: pyke_music
    password: PyKe_2709_music
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
      continue-on-error: true
  
  # JPA Config
  jpa:
    hibernate:
      ddl-auto: update
      #show-sql: true
    properties:
      hibernate:
        format-sql: true

security:
  jwt:
    secret: VGhpcy1pcy1hLXN1ZmZpY2llbnRseS1sb25nLXNlY3JldC1rZXktZm9yLUpXVHM=
    expirationMs: 60000  # 15 minutes
    refreshExpirationMs: 604800000 # 7 days

server:
  port: 8087
