spring:
  application:
    name: mvp
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  
  # DB config
  datasource:
    url: jdbc:postgresql://localhost:5437/music-db
    username: pyke_music
    password: PyKe_2709_music
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
      continue-on-error: true
  
  # JPA Config
  jpa:
    hibernate:
      ddl-auto: update
      #show-sql: true
    properties:
      hibernate:
        format-sql: true√π
  
  security:
    oauth2:
      resourceserver:
        jwt:  
          issuer-uri: "http://localhost:9097/realms/music-app"

test:
  frontend:
    url: https://0q4gh9cl-4200.uks1.devtunnels.ms


security:
  jwt:
    secret: VGhpcy1pcy1hLXN1ZmZpY2llbnRseS1sb25nLXNlY3JldC1rZXktZm9yLUpXVHM=
    expirationMs: 60000  # 15 minutes
    refreshExpirationMs: 604800000 # 7 days

server:
  port: 8087


keycloak:
  realm : music-app
  auth-server-url: http://localhost:9097
  resource: angular-client
  security-constraints[0]:
    authRoles[0]: USER  
    securityCollections[0]:
      patterns: /api/*